services:
  wow_tools:
    build:
      context: docker
      dockerfile: wowtools.Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - "${WOW_DIR}:/game"
    command: [ "/app/wow.tools.local", "-wowFolder", "/game" , "-region" , "eu", "-locale", "enUS" ]

  wow_tools_classic:
    build:
      context: docker
      dockerfile: wowtools.Dockerfile
    ports:
      - "5001:8080"
    volumes:
      - "${WOW_DIR}:/game"
    command: ["/app/wow.tools.local", "-wowFolder", "/game" , "-region" , "eu", "-wowProduct", "wow_classic", "-locale", "enUS" ]
