services:
  wow_tools:
    build:
      context: docker
      dockerfile: wowtools.Dockerfile
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    ports:
      - "5000:8080"
    volumes:
      - "${WOW_DIR}:/game"
    entrypoint: [ "./wow.tools.local", "-wowFolder", "/game" , "-region" , "eu" ]

  wow_tools_classic:
    build:
      context: docker
      dockerfile: wowtools.Dockerfile
    environment:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    ports:
      - "5001:8080"
    volumes:
      - "${WOW_DIR}:/game"
    entrypoint: [ "./wow.tools.local", "-wowFolder", "/game" , "-region" , "eu", "-product", "wow_classic" ]
