game_path: "/data/games/WoW/"
export_path: "/data/games/WoW/_retail_/Interface/AddOns/MountJournalEnhanced/Database"

db_files:
  - Mount
  - ItemEffect
  - SpellMisc
  - PlayerCondition
  - CreatureDisplayInfo
  - SpellEffect
  - CreatureModelData
  - ItemSparse
  - MountXDisplay
  - ItemXItemEffect
  - Achievement

ignored:
  - 7    # Gray Wolf
  - 15   # Winter Wolf
  - 28   # Skeletal Horse
  - 70   # Riding Kodo
  - 123  # Nether Drake
  - 238  # Swift Spectral Gryphon
  - 251  # Black Polar Bear
  - 273  # Grand Caravan Mammoth
  - 274  # Grand Caravan Mammoth
  - 308  # Blue Skeletal Warhorse
  - 333  # Magic Rooster
  - 334  # Magic Rooster
  - 335  # Magic Rooster
  - 776  # Swift Spectral Rylak
  - 786  # Charger
  - 934  # Swift Spectral Hippogryph
  - 987  # Valorous Charger
  - 989  # Vengeful Charger
  - 990  # Vigilant Charger
  - 991  # Golden Charger
  - 1269 # Swift Spectral Fathom Ray (inv_mount_hippogryph_arcane)
  - 1270 # Swift Spectral Magnetocraft (inv_mount_hippogryph_arcane)
  - 1271 # Swift Spectral Armored Gryphon (inv_mount_hippogryph_arcane)
  - 1272 # Swift Spectral Pterrordax (inv_mount_hippogryph_arcane)
  - 1578 # [DND] Test Mount JZB (ability_mount_travellersyakmount)
  - 1605 # Dragon Isles Drake Model Test
  - 1607 # Swift Spectral Drake
  - 1608 # Soar, Dracthyr racial
  - 1690 # Whelpling (dragonflying guest seat)
  - 1771 # Highland Drake (dragonriding races mountType=426)
  - 1786 # Renewed Proto-Drake (dragonriding races mountType=426)
  - 1787 # Windborne Velocidrake (dragonriding races mountType=426)
  - 1788 # Cliffside Wylderdrake (dragonriding races mountType=426)
  - 1789 # Winding Slitherdrake (dragonriding races mountType=426)
  - 1796 # Whelpling (dragonflying guest seat)
#  - 1823 # Swift Spectral Gryphon
  - 1952 # Soar, Dracthyr racial
  - 2115 # Soar, Dracthyr racial
  - 2301 # Unstable Rocket
  - 2302 # Unstable Rocket

# family based on http://www.warcraftmounts.com/gallery.php + https://warcraft.wiki.gg/wiki/Beast
# try to keep naming in singular

familymap: [
  { name: Amphibian,
    subfamily: [
      { name: Crawgs, wcm: [ Crawgs ] },
      { name: Toads, wcm: [ Toads ]},
    ]
  },
  { name: Arachnids,
    subfamily: [
      { name: Mite, wcm: [ Animites, Bloodswarmers, Swarmites ] },
      { name: Scorpions, wcm: [ Scorpions, Mechanical Scorpions]},
      { name: Spiders, wcm: [ Spiders ] },
    ]
  },
  { name: Bats, wcm: [ Bats, Felbats ], ids: [2309] }, # Chaos-Born Dreadwing (classic)
  { name: Birds,
    subfamily: [
      { name: Albatross, wcm: [ Birds ], icons: [ alabatross, albatross ] },
      { name: Chickens, wcm: [ Chickens ] },
      { name: Cranes, wcm: [ Cranes ], ids: [ 2636 ] }, # Celestial Riding Crane
      { name: Crows, wcm: [ Birds ], icons: [ roguemount, arcaneraven, suncrown, stormcrow ] },
      { name: Eagle, wcm: [ Birds ], icons: [ eagle ] },
      { name: Hawkstriders, wcm: [ Hawkstriders ] },
      { name: Mechanical Birds, wcm: [ Mechanical Birds ] },
      { name: Owl, wcm: [ Owls ] },
      { name: Owlbear, wcm: [ Owlbears ] },
      { name: Pandaren Phoenixes, wcm: [ Birds ], icons: [ pandarenphoenix, ji-kun, thunderislebirdboss ] },
      { name: Parrots, wcm: [ Birds ], icons: [ parrot ], ids: [ 2147 ] }, # Polly Roger (classic)
      { name: Peafowl, wcm: [ Birds ], icons: [ peacock ], ids: [ 2036 ] }, # Brilliant Sunburst Peafowl
      { name: Phoenixes, wcm: [ Phoenixes ], ids: [1905, 2255, 2478] }, # Green Fire Hawk (classic), Al'ars golden Ash, Blazing Royal Fire Hawk
      { name: Raptora, wcm: [ Birds ], icons: [ progenitorhawk ] },
      { name: Raven, wcm: [ Birds ], icons: [ ravenlord, dreadraven, ravenmount ] },
      { name: Roc, wcm: [ Deathrocs ], ids: [2505, 2549,2552] }, # K'arrocs
      { name: Tallstriders, wcm: [ Tallstriders ]},
      { name: Talonbirds, wcm: [ Talonbirds ] },
      { name: Vultures, wcm: [ Birds ], icons: [ vulture ] },
    ]
  },
  { name: Bovids,
    subfamily: [
      { name: Clefthooves, wcm: [ Clefthooves ] },
      { name: Goats, wcm: [ Goats ] },
      { name: Rams, wcm: [ Rams ] },
      { name: Ruinstriders, wcm: [ Talbuks ], icons: [ argustalbukmount, paladin_divinesteed, lightforgedtalbuk ], ids: [2630] }, # Ornery Breezestrider
      { name: Slateback, wcm: [ Slatebacks ], ids: [2560,2561,2655] },
      { name: Talbuks, wcm: [ Talbuks ], icons: [ foot_centaur, talbukdraenor ] },
      { name: Tauralus, wcm: [ Tauraluses ] },
      { name: Yaks, wcm: [ Yaks ] },
    ]
  },
  { name: Carnivorans,
    subfamily: [
      { name: Bears, wcm: [ Bears ], ids: [2262]}, # Harmonious Salutations Bear
      { name: Foxes, wcm: [ Foxes ] },
      { name: Gargon, wcm: [ Gargons ] },
      { name: Hounds, wcm: [ Dogs, Core Hounds, Felstalkers, Darkhounds, Soulseekers ] },
      { name: Hyenas, wcm: [ Hyenas ], ids: [2272, 2274, 2276, 2277] }, # Crimson Armored Growler, Blackwater Bonecrusher, Darkfuse Chompactor, Violet Armored Growler
      { name: Quilen, wcm: [ Quilen ] },
      { name: Vulpin, wcm: [ Vulpin ] },
      { name: Ottuk, wcm: [ Ottuks ] },
      { name: Meeksi, wcm: [ Meeksi ], ids: [2513, 2514, 2515, 2516, 2517] },
    ]
  },
  { name: Cats,
    subfamily: [
      { name: Bipedal Cat, wcm: [ Bipedal Cats ] },
      { name: Lions, wcm: [ Cats ], icons: [ lion, goldenking ], ids: [ 421 ] },                     # Winged Guardian
      { name: Manasabers, wcm: [ Cats ], icons: [ suramarmount, nightborneracial ], ids: [ 741 ] }, # Mystic Runesaber
      { name: Dreamsaber, wcm: [ Cats ], icons: [ dreamsaber ] },
      { name: Lynx, wcm: [ Cats ], icons: [ arathilynxmount ]  },
      { name: Mechanical Cats, wcm: [ Mechanical Cats ] },
      { name: Others, wcm: [ Flamesabers, Panthara, Felsabers, Undead Cats ], ids: [ 1330, 1531, 1576, 1577, 2235 ] }, # Sunwarmed Furline, Wen Lo, Jigglesworth Sr., Ash'adar, Starlined Furline
      { name: Sabers, wcm: [ Cats ], icons: [ blackpanther, whitetiger, pinktiger, nightsaber2, saber3mount, sabertooth, nightsaberhorde ] , ids: [2199, 2200]}, # [PH] Nightsaber Horde Mount
      { name: Stone Cats, wcm: [ Flying Stone Cats ], ids: [ 421 ] }, # Winged Guardian
      { name: Tigers, wcm: [ Cats, Undead Cats ], icons: [ monkmount, spectraltiger, siberiantiger, warnightsaber, jungletiger, shatiger ], ids: [2340, 2638] }, # Sha-Touched Riding Tiger (classic), Celestial Riding Tiger
    ]
  },
  { name: Crabs, wcm: [ Crabs ] },
  { name: Demons,
    subfamily: [
      { name: Demonic Hounds, wcm: [ Felstalkers, Vile Fiends, Antoran Hounds, Flying Felstalkers, Amalgams of Rage ] },
      { name: Demonic Steeds, wcm: [ Demonic Steeds ] },
      { name: Felsabers, wcm: [ Felsabers ] },
      { name: Infernals, wcm: [ Infernals ] },
      { name: "Ur'zul", wcm: [ "Ur'zul" ] },
    ]
  },
  { name: Devourer,
    subfamily: [
      { name: Animite, wcm: [ Animites ] },
      { name: Gorger, wcm: [ Anima Gorgers ], ids: [ 2602 ] }, # Translocated Gorger
      { name: Mauler, wcm: [ Devourer Maulers ], ids: [ 2603 ] }, # Sthaarbs's Last Lunch
    ]
  },
  { name: Dinosaurs,
    subfamily: [
      { name: Brutosaurs, wcm: [ Brutosaurs ] },
      { name: Direhorns, wcm: [ Direhorns ] },
      { name: Falcosaurs, wcm: [ Raptors ], icons: [ falcosauro ] },
      { name: Pterrordaxes, wcm: [ Pterrordaxes ] },
      { name: Raptors, wcm: [ Raptors, Undead Raptors ], icons: [ raptor ], ids: [ 2339 ] }, # Jani
    ]
  },
  { name: Dragonhawks, wcm: [ Dragonhawks ], ids: [1471] }, # Vengeance
  { name: Drakes,
    subfamily: [
      { name: Cloud Serpents, wcm: [ Cloud Serpents ], ids: [2341, 2639] }, # Sha-Touched Cloud Serpent (classic), Celestial Riding Serpent
      { name: Drakes, wcm: [ Drakes, Onyxian Drakes, Void Dragons ], ids: [ 1770, 1832, 2260, 2569, 2606 ] }, # Festering Emerald, Nightmarish Emerald, Lava Drake (all classic), Unbound Star-Eater, Royal Voidwing
      { name: Grand Drakes, wcm: [ Grand Drakes ] },
      { name: Nether Drakes, wcm: [ Nether Drakes ] },
      { name: Others, wcm: [ Sinuous Drakes, Fey Drakes, Everwyrms, Mechanical Dragons, Greatwyrms, Wyvern Drakes, Pterrordax Drakes ] },
      { name: Proto-Drakes, wcm: [ Proto-Drakes ], },
      { name: Stone Drakes, wcm: [ Stone Drakes ] },
      { name: Undead Drakes, wcm: [ Undead Drakes, Soul Eaters ] },
      { name: Wind Drakes, wcm: [ Wind Drakes ] },
    ]
  },
  { name: Elementals,
    subfamily: [
      { name: Core Hounds, wcm: [ Core Hounds ] },
      { name: Phoenixes, wcm: [ Phoenixes ] },
      { name: Sabers, wcm: [ Flamesabers ] },
      { name: Stone Drakes, wcm: [ Stone Drakes ] },
      { name: Wind Drakes, wcm: [ Wind Drakes ] },
      { name: Sporebat, wcm: [ Shalewings ] },
      { name: Others, wcm: [ Elementals, Ancients ], ids: [ 1807 ] }, # Avatar of Flame (classic)
    ]
  },
  { name: Feathermanes,
    subfamily: [
      { name: Gryphons, wcm: [ Gryphons, Undead Gryphons ], ids: [ 2312,2626,2627,2628,2629 ] }, # Chaos-Born Gryphon (classic), Adorned Northeron Gryphon,, High Shaman's Aerie Gryphon, Cinder-Plumed Highland Gryphon, Emberwing Sky Guide
      { name: Hippogryphs, wcm: [ Hippogryphs ], ids: [ 2311 ] }, # Chaos-Born Hippogryph (classic)
      { name: Larion, wcm: [ Larions ] },
      { name: Wolfhawks, wcm: [ Wolfhawks ] },
      { name: Wyverns, wcm: [ Wind Riders, Undead Wind Riders ], ids: [ 2310 ] }, # Chaos-Born Wind Rider (classic)
    ]
  },
  { name: Fish,
    subfamily: [
      { name: Fish, wcm: [ Fish ], ids: [ 2186 ] }, # [PH] Blue Old God Fish Mount
      { name: Seahorses, wcm: [ Seahorses, Hippocampuses ], ids: [1873] }, # Abyssal Seahorse (classic)
      { name: Stingrays, wcm: [ Stingrays ] },
    ]
  },
  { name: Gargoyle, wcm: [ Gargoyles ] },
  { name: Hedgehog, wcm: [ Hedgehogs ] },
  { name: Horses,
    subfamily: [
      { name: Chargers,
        wcm: [ Horses ],
        icons: [ _paladinmount_, _charger, nature_swiftness, alliancepvpmount, vicioushorse, paladin_divinesteed, horsekultiran, hordehorse, darkmoonhorse ],
        ids: [
          341, # Argent Warhorse
          344, # Crusader's White Warhorse
          345, # Crusader's Black Warhorse
          2497, # Void-Forged Stallion
        ]
      },
      { name: Demonic Steeds,
        wcm: [ Demonic Steeds ],
        ids: [
          898, # Netherlord's Chaotic Wrathsteed
          930, # Netherlord's Brimstone Wrathsteed
          931, # Netherlord's Accursed Wrathsteed
        ]
      },
      { name: Flying Steeds, wcm: [ Flying Steeds ], ids: [2622,2623,2624,2625] }, # The Headless Horseman's Chargers
      { name: Horned Steeds, wcm: [ Horned Steeds, Windsteeds ], ids: [2488] }, # Shimmermist Free Runner
      { name: Mechanical Steeds, wcm: [ Mechanical Steeds ] },
      { name: Mountain Horses,
        wcm: [ Horses ],
        icons: [ dressedhorse, horse3 ],
        ids: [
          435, # Mountain Horse
          436, # Swift Mountain Horse
        ]
      },
      { name: Steeds, wcm: [ Horses ], icons: [ ridinghorse, nightmarehorse ] },
      { name: Undead Steeds, wcm: [ Undead Steeds ] },
    ]
  },
  { name: Humanoids,
    subfamily: [
      { name: Gronnlings, wcm: [ Gronnlings ] },
      { name: Gorger, wcm: [ Anima Gorgers ] },
      { name: Murloc, wcm: [ Murlocs ] },
      { name: Yetis, wcm: [ Yeti ] },
    ]
  },
  { name: Insects,
    subfamily: [
      { name: Aqir Flyers, wcm: [ Aqir Flyers ] },
      { name: Beetle, wcm: [ Beetles ] },
      { name: Gorm, wcm: [ Gorms ] },
      { name: Flies, wcm: [ Flies, Skitterflies ] },
      { name: Krolusks, wcm: [ Krolusks ], ids: [2601] }, # Pearlescent Krolusk
      { name: Moth, wcm: [ Moths ] },
      { name: Others, wcm: [ Bees, Ravagers ] },
      { name: Silithids, wcm: [ Silithids ],
        ids: [
          936, # Red Qiraji War Tank
          935, # Blue Qiraji War Tank
        ] },
      { name: Skyrazor, wcm: [ Skyrazors ] },
      { name: Void Creeper, ids: [2555, 2556,2557,2570,2571] }, # Bone Freezer, Ruby/Acidic/Vicious(2x) Void Creeper
      { name: Void Flyer, ids: [2510, 2511,2631,2633] }, # Terror of the Wastes, Terror of the Night, Scarlet/azure Void Flyer
      { name: Water Striders, wcm: [ Water Striders ], ids: [489,490, 491] }, # Orange, Jade and Golden Water Strider (mop classic)
      { name: Wasp, wcm: [ Wasps ] },
    ]
  },
  { name: Jellyfish, wcm: [ Fathom Dwellers, Hiveminds, Aurelids ] },
  { name: Mole, wcm: [ Moles ] },
  { name: Mollusc,
    subfamily: [
      { name: Snail, wcm: [ Snails ], ids: [2495] }, # Emerald Snail
      { name: Slug, wcm: [ Slugs ] },
    ] },
  { name: Rays,
    subfamily: [
      { name: Fathom Rays, wcm: [ Fathom Rays ] },
      { name: Mana Rays, wcm: [ Mana Rays ] },
      { name: Nether Rays, wcm: [ Nether Rays ] },
      { name: Stingrays, wcm: [ Stingrays ] },
    ]
  },
  { name: Razorwing, wcm: [ Razorwings ] },
  { name: Reptiles,
    subfamily: [
      { name: Armoredon, wcm: [ Armoredons ], ids: [ 2055] }, # Infinite Armoredon
      { name: Basilisks, wcm: [ Basilisks ] },
      { name: Crocolisks, wcm: [ Crocolisks, Flying Crocolisks ], ids: [2594] }, # Envoy of Sa'bak (classic)
      { name: Kodos, wcm: [ Kodos ], ids: [ 225, 1869, 1870] }, #Brewfest Riding Kodo, (Sunwalker Kodo classic)
      { name: Mushan, wcm: [ Mushan ] },
      { name: N'Zoth Serpents, wcm: [ N'Zoth Serpents ] },
      { name: Sea Serpents, wcm: [ Sea Serpents ] },
      { name: Snapdragons, wcm: [ Snapdragons ] },
      { name: Shardhides, wcm: [ Shardhides ] },
      { name: Turtles, wcm: [ Dragon Turtles, Sea Turtles, Turtles ] },
      { name: Thunder Lizard, wcm: [ Thunder Lizards ] },
      { name: Others, wcm: [ Warp Stalkers, Newts, Flying Snakes ], ids: [ 1761 ] }, # Reawakened Phase-Hunter (classic)
    ]
  },
  { name: Rylaks, wcm: [ Rylaks, Chimaeras ] },
  { name: Rodent,
    subfamily: [
      { name: Rats, wcm: [ Rats, Mawrats ] },
      { name: Rabbit, wcm: [ Rabbits ], ids: [ 1769 ] }, # Hao-Yue (classic)
    ] },
  { name: Ungulates,
    subfamily: [
      { name: Alpacas, wcm: [ Alpacas ] },
      { name: Boars, wcm: [ Boars, Divine Boars, Skullboars ] },
      { name: Camels, wcm: [ Camels ] },
      { name: Cervid, wcm: [ Cervids ] },
      { name: Elekks, wcm: [ Elekks ], ids: [1871, 1872, 2618, 2619, 2620, 2621] }, # Exarch's Elekk (classic), 11.2 Elekks
      { name: Mammoths, wcm: [ Mammoths ] },
      { name: Moose, wcm: [ Elderhorns, Bruffalons ] },
      { name: Ox, wcm: [ Oxen ], ids: [ 2637 ] }, # Celestial Riding Ox
      { name: Rhinos, wcm: [ Rhinos ] },
      { name: Riverbeasts, wcm: [ Riverbeasts ] },
      { name: Stag, wcm: [ Runestags, Dreamstags ] },
    ]
  },
  { name: Vehicles,
    subfamily: [
      { name: Airplanes, wcm: [ Airplanes ] },
      { name: Airships, wcm: [ Skyships, Zeppelins, Flying Ships ], ids: [2512] }, # Delver's Mana-Skimmer
      { name: Assault Wagons, wcm: [ Assault Wagons ] },
      { name: Book, wcm: [ Books ] },
      { name: Broom, wcm: [ Magical Broomsticks ] },
      { name: Carpets, wcm: [ Flying Carpets ] },
      { name: Discs, wcm: [ Discs ], ids: [1482, 1483] }, # Xy & Vandal's Gearglider
      { name: Gyrocopters, wcm: [ Gyrocopters ], ids: [2640] }, # Brewfest Bomber
      { name: Hands, wcm: [ Undead Hands ] },
      { name: Hovercraft, wcm: [ Hovercraft ] },
      { name: "Hover Board", wcm: [ "Hover Boards", "Flying Chessboards" ] },
      { name: Jet Aerial Units, wcm: [ Jet Aerial Units ] },
      { name: Kites, wcm: [ Kites, Gliders ], ids: [ 1762 ] }, # Kalu'ak Whalebone Glider (classic)
      { name: Mecha-suits, wcm: [ Flying Mecha-suits ] },
      { name: Mechanical Animals, wcm: [ Mechanical Scorpions, Mechanical Steeds, Mechanical Birds, Mechanical Cats, Mechanical Dragons, Mechanical Devilsaurs ] },
      { name: Mechanostriders, wcm: [ Mechanostriders ] },
      { name: Motorcycles, wcm: [ Motorcycles, Monocycles ] },
      { name: Rockets, wcm: [ Rockets ] },
      { name: Seat, wcm: [ Flying Seats ] },
      { name: Spider Tanks, wcm: [ Spider Tanks, Flying Spider Tanks ] },
    ]
  },
  { name: Vombata, wcm: [ Wombats ], icons: [ progenitorwombat ] },
  { name: Wolves,
    subfamily: [
      { name: Dire Wolves, wcm: [ Wolves ], icons: [ wolfdraenor, orcclanworg ], ids: [ 657 ] }, # Garn Nighthowl
      { name: Lupine, wcm: [ Wolves ], icons: [ progenitorwolf, vicioushordewolf, viciousalliancewolf ] },
      { name: Undead Wolves, wcm: [ Undead Wolves ] },
      { name: War Wolves, wcm: [ Wolves ], icons: [ _hordepvpmount, _alliancewolf, armoredwolf, frostwolfhowler ], ids: [ 2202, 2203 ] }, # [PH] Alliance  Wolf
      { name: Wilderlings, wcm: [ Wilderlings ] },
      { name: Wolves, wcm: [ Wolves ], icons: [ direwolf ], ids: [ 51 ] }, # Arctic Wolf
    ]
  },
  { name: Worm, wcm: [ Jawcrawlers ] },
]